apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carts
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: revive
  source:
    repoURL: 'https://github.com/PrinceDalton/revive-app.git'
    path: helm-charts/helm-chart-1/carts
    targetRevision: main
    #directory:
     # recurse: true
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
    prerequisites:
    - createNamespace: true
